

services:
  backend:
    build:
      context: ./mysite
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sweetcakes
      POSTGRES_USER: helen
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: