# Generated by Django 5.2 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desert',
            name='category',
            field=models.CharField(choices=[('cheesecake', 'Чизкейк'), ('mochi', 'Моти'), ('macaron', 'Макарунс'), ('pastry', 'Пирожное'), ('cake', 'Торт')], default='cheesecake', max_length=50),
            preserve_default=False,
        ),
    ]
